openapi: "3.0.3"
info:
  title: Play moduler monolith API
  version: "1.0"
servers:
  - url: http://localhost:9000/
    description: local

tags:
  - name: users
    description: Access to Users
paths:
  /users:
    get:
      tags:
        - users
      summary: get users
      responses:
        '200':
          description: OK
